// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compute_kernel
void compute_kernel();
RcppExport SEXP _FastGKMSVM_compute_kernel() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    compute_kernel();
    return R_NilValue;
END_RCPP
}
// fit
void fit();
RcppExport SEXP _FastGKMSVM_fit() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    fit();
    return R_NilValue;
END_RCPP
}
// score
double score();
RcppExport SEXP _FastGKMSVM_score() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(score());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastGKMSVM_compute_kernel", (DL_FUNC) &_FastGKMSVM_compute_kernel, 0},
    {"_FastGKMSVM_fit", (DL_FUNC) &_FastGKMSVM_fit, 0},
    {"_FastGKMSVM_score", (DL_FUNC) &_FastGKMSVM_score, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastGKMSVM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
