# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' FastSK: A Fast and Accurate GKM-SVM
#'
#' @name fastsk_compute_kernel
#' @description Computes the kernel for a GKM-SVM
#' @param train_file A FASTA file containing training sequences and their label
#' @param test_file A FASTA file containing testing sequences and their label
#' @param g The length of the substrings used to compare sequences. Constraints: \code{0 < g < 20}
#' @param m The maximum number of mismatches when comparing two gmers Constraints: \code{0 <= m < g}
#' @param t The number of threads to used. Default is 1
#' @param approx A boolean; if set to true, then the fast approximation algorithm is used to compute the kernel. Default is False
#' @param delta Default is 0.025
#' @param max_iters The maximum number of iterations to run. Default is 100
#' @param skip_variance Default is False
#' @param dictionary_file A file containing the alphabet of characters appearing in the sequences. If not provided, the dictionary will be inferred
#' @export
fastsk_compute_kernel <- function(train_file, test_file, out_file, g, m, t = 1L, approx = FALSE, delta = 0.025, max_iters = 100L, skip_variance = FALSE, dictionary_file = "") {
    invisible(.Call(`_FastGKMSVM_fastsk_compute_kernel`, train_file, test_file, out_file, g, m, t, approx, delta, max_iters, skip_variance, dictionary_file))
}

#' FastSK: A Fast and Accurate GKM-SVM
#'
#' @name fastsk_train_and_score
#' @description Trains a fast and accurate gkm-svm and scores on test sequences
#' @param train_file A FASTA file containing training sequences and their label
#' @param test_file A FASTA file containing testing sequences and their label
#' @param g The length of the substrings used to compare sequences. Constraints: \code{0 < g < 20}
#' @param m The maximum number of mismatches when comparing two gmers Constraints: \code{0 <= m < g}
#' @param t The number of threads to used. Default is 1
#' @param approx A boolean; if set to true, then the fast approximation algorithm is used to compute the kernel. Default is False
#' @param delta Default is 0.025
#' @param max_iters The maximum number of iterations to run. Default is 100
#' @param skip_variance Default is False
#' @param C SVM C parameter. Default is 1.0
#' @param nu SVM nu parameter. Default is 1.0
#' @param eps SVM epsilon parameter. Defult is 1.0
#' @param kernel_type The kernel type to used. Must be one of linear (default), fastsk, or rbf
#' @param dictionary_file A file containing the alphabet of characters appearing in the sequences. If not provided, the dictionary will be inferred
#' @param metric The metric to score the test sequences with. Must be one of auc (default) or accuracy
#' @param metric_file A filepath to write the test sequence predictions. Default is auc_file.txt
#' @export
fastsk_train_and_score <- function(train_file, test_file, g, m, t = 1L, approx = FALSE, delta = 0.025, max_iters = 100L, skip_variance = FALSE, C = 1.0, nu = 1.0, eps = 1.0, kernel_type = "linear", dictionary_file = "", metric = "auc", metric_file = "auc_file.txt") {
    invisible(.Call(`_FastGKMSVM_fastsk_train_and_score`, train_file, test_file, g, m, t, approx, delta, max_iters, skip_variance, C, nu, eps, kernel_type, dictionary_file, metric, metric_file))
}

