# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_kernel <- function() {
    invisible(.Call(`_FastGKMSVM_compute_kernel`))
}

fit <- function() {
    invisible(.Call(`_FastGKMSVM_fit`))
}

score <- function() {
    .Call(`_FastGKMSVM_score`)
}

